import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <header className="max-w-3xl flex items-center py-8 gap-4 px-16 w-full mx-auto *:font-bold *:text-gray-300 *:transition-colors *:hover:text-white">
                    <Link href="/">Home</Link>
                    <Link href="/contact">Contact</Link>
                </header>
                {children}
            </body>
        </html>
    );
}
